// ============================================================
// MASTER DATA - Device Types, Makes, Users, and Options
// ============================================================

// Policy Circular Reference
export const POLICY_CIRCULAR = "MD/MK/CGM(HR&A)/2659-2660 dated: 30-06-2023";

// Device Types
export const INITIAL_DEVICE_TYPES = [
  { code: 1, name: "Desktop" },
  { code: 2, name: "Printer" },
  { code: 3, name: "UPS" },
  { code: 4, name: "Laptop" },
  { code: 5, name: "Scanner" },
  { code: 6, name: "LED TV" },
  { code: 7, name: "Mobile Phone" },
  { code: 8, name: "Finger Biometric" },
  { code: 9, name: "IRIS" },
  { code: 10, name: "Multifunction Printer" },
  { code: 11, name: "A3 Multifunction Printer" },
  { code: 12, name: "Monitor" },
  { code: 13, name: "CPU" },
  { code: 14, name: "Keyboard" },
  { code: 15, name: "Mouse" },
  { code: 16, name: "LPRF Module" },
  { code: 17, name: "Telephones" },
  { code: 18, name: "Dongle" },
  { code: 19, name: "All In One PC" },
  { code: 20, name: "PoS Machine" },
  { code: 22, name: "Tablet" },
  { code: 23, name: "Dot Matrix Printer" },
  { code: 24, name: "Assembled CPU" },
  { code: 25, name: "Switch" },
  { code: 26, name: "Router" },
  { code: 27, name: "QR Code Printer" },
];

// Makes/Brands for each device type
export const INITIAL_MAKES = [
  { code: 11, name: "Acer", deviceCode: 1 },
  { code: 12, name: "Dell", deviceCode: 1 },
  { code: 13, name: "HCL", deviceCode: 1 },
  { code: 14, name: "Assembled", deviceCode: 1 },
  { code: 21, name: "Samsung", deviceCode: 2 },
  { code: 22, name: "HP", deviceCode: 2 },
  { code: 23, name: "Canon", deviceCode: 2 },
  { code: 24, name: "Ricoh", deviceCode: 2 },
  { code: 25, name: "Brother", deviceCode: 2 },
  { code: 26, name: "Epson", deviceCode: 2 },
  { code: 31, name: "BPE", deviceCode: 3 },
  { code: 32, name: "Intex", deviceCode: 3 },
  { code: 33, name: "Uniline", deviceCode: 3 },
  { code: 34, name: "Emerson", deviceCode: 3 },
  { code: 35, name: "Arrow", deviceCode: 3 },
  { code: 36, name: "Luminous", deviceCode: 3 },
  { code: 37, name: "Cyber Power", deviceCode: 3 },
  { code: 38, name: "ZEBION", deviceCode: 3 },
  { code: 41, name: "Acer", deviceCode: 4 },
  { code: 42, name: "HP", deviceCode: 4 },
  { code: 43, name: "Lenovo", deviceCode: 4 },
  { code: 44, name: "Dell", deviceCode: 4 },
  { code: 51, name: "Canon", deviceCode: 5 },
  { code: 52, name: "Epson", deviceCode: 5 },
  { code: 61, name: "Samsung", deviceCode: 6 },
  { code: 62, name: "Sony", deviceCode: 6 },
  { code: 63, name: "LG", deviceCode: 6 },
  { code: 64, name: "Videocon", deviceCode: 6 },
  { code: 71, name: "Intex", deviceCode: 7 },
  { code: 81, name: "Mantra", deviceCode: 8 },
  { code: 91, name: "Irishield", deviceCode: 9 },
  { code: 101, name: "Samsung", deviceCode: 10 },
  { code: 102, name: "Canon", deviceCode: 10 },
  { code: 103, name: "HP", deviceCode: 10 },
  { code: 104, name: "Brother", deviceCode: 10 },
  { code: 111, name: "HP", deviceCode: 11 },
  { code: 112, name: "Samsung", deviceCode: 11 },
  { code: 113, name: "Brother", deviceCode: 11 },
  { code: 114, name: "Canon", deviceCode: 11 },
  { code: 121, name: "Acer", deviceCode: 12 },
  { code: 122, name: "HP", deviceCode: 12 },
  { code: 123, name: "Dell", deviceCode: 12 },
  { code: 124, name: "Compaq", deviceCode: 12 },
  { code: 125, name: "Lenovo", deviceCode: 12 },
  { code: 126, name: "HCL", deviceCode: 12 },
  { code: 127, name: "LG", deviceCode: 12 },
  { code: 131, name: "Dell", deviceCode: 13 },
  { code: 132, name: "HP", deviceCode: 13 },
  { code: 133, name: "HCL", deviceCode: 13 },
  { code: 134, name: "Assembled", deviceCode: 13 },
  { code: 135, name: "Lenovo", deviceCode: 13 },
  { code: 136, name: "LG", deviceCode: 13 },
  { code: 137, name: "Acer", deviceCode: 13 },
  { code: 141, name: "HP", deviceCode: 14 },
  { code: 142, name: "Acer", deviceCode: 14 },
  { code: 143, name: "Logitech", deviceCode: 14 },
  { code: 144, name: "Dell", deviceCode: 14 },
  { code: 151, name: "HP", deviceCode: 15 },
  { code: 152, name: "Acer", deviceCode: 15 },
  { code: 153, name: "Logitech", deviceCode: 15 },
  { code: 154, name: "Dell", deviceCode: 15 },
  { code: 161, name: "DRMZ", deviceCode: 16 },
  { code: 171, name: "Binatone", deviceCode: 17 },
  { code: 172, name: "Euroset", deviceCode: 17 },
  { code: 181, name: "D-Link", deviceCode: 18 },
  { code: 191, name: "Lenovo", deviceCode: 19 },
  { code: 244, name: "Acer", deviceCode: 19 },
  { code: 201, name: "Mosambee", deviceCode: 20 },
  { code: 221, name: "Lenovo", deviceCode: 22 },
  { code: 231, name: "EPSON", deviceCode: 23 },
  { code: 241, name: "ZEBION", deviceCode: 24 },
  { code: 242, name: "Cisco", deviceCode: 25 },
  { code: 243, name: "Cisco", deviceCode: 26 },
  { code: 245, name: "Udyama", deviceCode: 27 },
  { code: 246, name: "Apple", deviceCode: 7 },
  { code: 247, name: "Samsung", deviceCode: 7 },
  { code: 248, name: "Microsoft", deviceCode: 22 },
  { code: 249, name: "ELNOVA", deviceCode: 3 },
];

// Initial system users (access_level_code: 1=Master Admin, 2=Corporate Admin, 3=Circle User)
export const INITIAL_USERS = [
  {
    id: 1,
    loginName: "Admin",
    loginId: "admin",
    password: "Pass@123",
    fullName: "siddharth_jain",
    role: "Master Admin",
    accessLevel: 1,
    circleCode: 0,
    regionCode: 0,
    status: "enabled",
    designation: "Manager IT",
    mobile: "9876500000",
    empCode: "SDHJAIN001",
  },
  {
    id: 2,
    loginName: "Corporate",
    loginId: "ams_corporate",
    password: "Pass@123",
    fullName: "Corporate Admin",
    role: "Corporate Admin",
    accessLevel: 2,
    circleCode: 0,
    regionCode: 0,
    status: "enabled",
    designation: "Account Officer",
    mobile: "9876500001",
    empCode: "CORP001",
  },
  {
    id: 3,
    loginName: "GM-O&M Bhopal",
    loginId: "gm_o&m_bhopal",
    password: "Pass@123",
    fullName: "GM-O&M Bhopal",
    role: "Circle User",
    accessLevel: 3,
    circleCode: 201,
    regionCode: 2,
    status: "enabled",
    designation: "General Manager",
    mobile: "6232913600",
    empCode: "93421418",
  },
  {
    id: 4,
    loginName: "GM-O&M Vidisha",
    loginId: "gm_o&m_vidisha",
    password: "Pass@123",
    fullName: "GM-O&M Vidisha",
    role: "Circle User",
    accessLevel: 3,
    circleCode: 207,
    regionCode: 2,
    status: "enabled",
    designation: "General Manager",
    mobile: "6232913800",
    empCode: "92386266",
  },
  {
    id: 5,
    loginName: "GM-City Bhopal",
    loginId: "gm_city_bhopal",
    password: "Pass@123",
    fullName: "GM-City Circle Bhopal",
    role: "Circle User",
    accessLevel: 3,
    circleCode: 203,
    regionCode: 2,
    status: "enabled",
    designation: "General Manager",
    mobile: "6232913400",
    empCode: "93326096",
  },
];

// Asset status options
export const STATUS_OPTIONS = [
  "Within Warranty Period",
  "Beyond Warranty Period",
  "Under Repair",
  "In Transit",
  "Disposed",
  "Lost/Stolen",
];

// Designation options
export const DESIGNATIONS = [
  "CMD",
  "MD",
  "CGM",
  "GM",
  "DGM",
  "Chief Engineer",
  "Superintending Engineer",
  "Executive Engineer",
  "Assistant Engineer",
  "Junior Engineer",
  "Account Officer",
  "Senior Account Officer",
  "Manager IT",
  "Computer Operator",
  "MIS Executive",
  "Junior Engineer IT",
  "Superintendent",
  "Assistant Superintendent",
  "Steno",
  "Assistant",
  "Other",
];

// Document types
export const DOC_TYPES = [
  "Purchase Order",
  "Invoice",
  "Government Circular",
  "Office Order",
  "Work Order",
  "Warranty Card",
  "AMC Agreement",
  "Service Report",
  "Other",
];

// Gate pass counter initial value
export let GP_COUNTER = 1000000042;

// Function to increment gate pass counter
export const incrementGPCounter = () => {
  GP_COUNTER++;
};

// Function to reset gate pass counter (for testing or admin purposes)
export const resetGPCounter = (value = 1000000042) => {
  GP_COUNTER = value;
};
